#!/usr/bin/env perl
use File::Basename;
use File::Path qw(make_path);
use Cwd;

# Global LaTeX Mk configuration for LuaLaTeX with Japanese support
$pdf_mode = 4;  # Use lualatex
$postscript_mode = 0;
$dvi_mode = 0;

# Default LuaLaTeX command (removed -halt-on-error for smoother continuous builds)
$lualatex = 'lualatex -synctex=1 -interaction=nonstopmode -file-line-error %O %S';

# Use biber for bibliography
$biber = 'biber %O --bblencoding=utf8 -u -U --output_safechars %B';
$bibtex_use = 2;

# Default directory settings
$aux_dir = 'aux';
$out_dir = 'out';

# Ensure directories exist
make_path($aux_dir) unless -d $aux_dir;
make_path($out_dir) unless -d $out_dir;

# Clean up settings - Added more extensions for a thorough clean
$clean_ext = 'auxlock figlist makefile run.xml synctex.gz fls fdb_latexmk idx ind ilg glo gls glg nav snm vrb bak sav fmt log bbl bcf blg toc lof lot';

# Preview settings
$preview_continuous_mode = 1;
$sleep_time = 1;
$max_repeat = 3;

# Font settings for various systems
if (-d '/mnt/c/Windows/Fonts') {
    $ENV{'OSFONTDIR'} = '/mnt/c/Windows/Fonts:/usr/local/share/fonts:/usr/share/fonts:/System/Library/Fonts';
} elsif (-d '/System/Library/Fonts') {
    # macOS
    $ENV{'OSFONTDIR'} = '/System/Library/Fonts:/Library/Fonts:/usr/local/share/fonts';
} else {
    # Linux
    $ENV{'OSFONTDIR'} = '/usr/local/share/fonts:/usr/share/fonts';
}

# CRITICAL FIX: Proper LuaTeX cache setup
my $home = $ENV{HOME};
my $cache_dir = "$home/.cache/luatex";
my $texmf_cache = "$home/.cache/texlive";
my $luaotfload_cache = "$cache_dir/luaotfload";

# Create all necessary cache directories with proper permissions
make_path($cache_dir, { mode => 0755 }) unless -d $cache_dir;
make_path($texmf_cache, { mode => 0755 }) unless -d $texmf_cache;
make_path($luaotfload_cache, { mode => 0755 }) unless -d $luaotfload_cache;

# Set environment variables for LuaTeX caching
$ENV{'TEXMFCACHE'} = $texmf_cache;
$ENV{'TEXMFVAR'} = $texmf_cache;
$ENV{'LUAOTFLOADPATH'} = $luaotfload_cache;

# Additional LuaTeX environment variables
$ENV{'LUATEX_CACHE_DIR'} = $cache_dir;
$ENV{'LUAOTFLOAD_NAMES_DIR'} = "$luaotfload_cache/names";
$ENV{'LUAOTFLOAD_CACHE_DIR'} = $luaotfload_cache;

# Create subdirectories for LuaOTFLoad
make_path("$luaotfload_cache/names", { mode => 0755 }) unless -d "$luaotfload_cache/names";
make_path("$luaotfload_cache/fonts", { mode => 0755 }) unless -d "$luaotfload_cache/fonts";

# LuaTeX optimizations
$warnings_as_errors = 0;
$ENV{'LANG'} = 'C.UTF-8';
