# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

[[repos]]
repo = "builtin"
hooks = [
    { id = "check-added-large-files" },
    { id = "check-case-conflict" },
    { id = "check-merge-conflict" },
    { id = "check-symlinks" },
    { id = "check-yaml", exclude = { glob = "**/*.tmpl" } },
    { id = "check-toml", exclude = { glob = "**/*.tmpl" } },
    { id = "check-json", exclude = { glob = "**/*.tmpl" } },
    { id = "detect-private-key" },
    { id = "end-of-file-fixer" },
    { id = "trailing-whitespace" },
]

[[repos]]
repo = "local"
hooks = [
    { id = "check-chezmoi-template-syntax", name = "Check chezmoi template syntax", entry = "bash -c 'for f; do chezmoi execute-template --init < \"$f\" > /dev/null || exit 1; done' --", language = "system", files = '\.tmpl$' }
]
